name: fatora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.5+1
  percent_indicator: ^4.2.5
  intl: ^0.20.2
  uuid: ^4.5.1
  font_awesome_flutter: ^10.5.0
  simple_icons: ^14.6.1
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  
  # Local Database
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  
  # Code Generation
  isar_generator: 3.1.0+1
  build_runner: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/